In [1]:
import torch
from torch import nn

In [2]:
model = nn.Linear(10, 1)

In [3]:
from adam_atan2_pytorch.adam_atan2 import AdamAtan2
from adam_atan2_pytorch.adam import Adam

In [4]:
opt = Adam(model.parameters(), lr = 1e-4)

In [5]:
for _ in range(100):
    loss = model(torch.randn(10))
    print(loss)
    loss.backward()

    opt.step()
    opt.zero_grad()

tensor([0.4849], grad_fn=<AddBackward0>)
tensor([0.0140], grad_fn=<AddBackward0>)
tensor([0.3703], grad_fn=<AddBackward0>)
tensor([-0.2269], grad_fn=<AddBackward0>)
tensor([0.0690], grad_fn=<AddBackward0>)
tensor([-0.6051], grad_fn=<AddBackward0>)
tensor([1.0430], grad_fn=<AddBackward0>)
tensor([-0.2708], grad_fn=<AddBackward0>)
tensor([0.3395], grad_fn=<AddBackward0>)
tensor([0.5088], grad_fn=<AddBackward0>)
tensor([-0.1463], grad_fn=<AddBackward0>)
tensor([0.5281], grad_fn=<AddBackward0>)
tensor([-0.9807], grad_fn=<AddBackward0>)
tensor([0.2824], grad_fn=<AddBackward0>)
tensor([1.0963], grad_fn=<AddBackward0>)
tensor([0.4211], grad_fn=<AddBackward0>)
tensor([-0.3287], grad_fn=<AddBackward0>)
tensor([-0.3031], grad_fn=<AddBackward0>)
tensor([0.6282], grad_fn=<AddBackward0>)
tensor([-0.1543], grad_fn=<AddBackward0>)
tensor([-0.2436], grad_fn=<AddBackward0>)
tensor([-0.2526], grad_fn=<AddBackward0>)
tensor([0.2858], grad_fn=<AddBackward0>)
tensor([-0.0408], grad_fn=<AddBackward0>)
tenso