In [6]:
import torch
from torch import nn

In [7]:
model = nn.Linear(10, 1)

In [8]:
from adam_atan2_pytorch.adam_atan2 import AdamAtan2
from adam_atan2_pytorch.adam import Adam

In [9]:
opt = AdamAtan2(model.parameters(), lr = 1e-4)

In [10]:
for _ in range(100):
    loss = model(torch.randn(10))
    print(loss)
    loss.backward()

    opt.step()
    opt.zero_grad()

tensor([0.5081], grad_fn=<AddBackward0>)
tensor([-0.7780], grad_fn=<AddBackward0>)
tensor([-0.0715], grad_fn=<AddBackward0>)
tensor([-0.9616], grad_fn=<AddBackward0>)
tensor([0.8527], grad_fn=<AddBackward0>)
tensor([0.2301], grad_fn=<AddBackward0>)
tensor([0.0387], grad_fn=<AddBackward0>)
tensor([-1.0102], grad_fn=<AddBackward0>)
tensor([-0.1313], grad_fn=<AddBackward0>)
tensor([0.5027], grad_fn=<AddBackward0>)
tensor([-0.6924], grad_fn=<AddBackward0>)
tensor([-1.2139], grad_fn=<AddBackward0>)
tensor([-0.6623], grad_fn=<AddBackward0>)
tensor([0.5148], grad_fn=<AddBackward0>)
tensor([0.0584], grad_fn=<AddBackward0>)
tensor([-0.0637], grad_fn=<AddBackward0>)
tensor([-0.1712], grad_fn=<AddBackward0>)
tensor([0.4234], grad_fn=<AddBackward0>)
tensor([-0.7570], grad_fn=<AddBackward0>)
tensor([0.3910], grad_fn=<AddBackward0>)
tensor([0.0536], grad_fn=<AddBackward0>)
tensor([-0.9070], grad_fn=<AddBackward0>)
tensor([0.1549], grad_fn=<AddBackward0>)
tensor([-0.6407], grad_fn=<AddBackward0>)
ten