In [6]:
import torch
from torch import nn

In [7]:
model = nn.Linear(10, 1)

In [11]:
from adam_atan2_pytorch.adam_atan2 import AdamAtan2
from adam_atan2_pytorch.adam import Adam
from adam_atan2_pytorch.adopt import Adopt

In [14]:
opt = Adopt(model.parameters(), lr = 1e-4)

In [15]:
for _ in range(100):
    loss = model(torch.randn(10))
    print(loss)
    loss.backward()

    opt.step()
    opt.zero_grad()

tensor([0.0195], grad_fn=<AddBackward0>)
tensor([0.1518], grad_fn=<AddBackward0>)
tensor([0.2942], grad_fn=<AddBackward0>)
tensor([0.1752], grad_fn=<AddBackward0>)
tensor([-0.6096], grad_fn=<AddBackward0>)
tensor([-0.0597], grad_fn=<AddBackward0>)
tensor([-0.3674], grad_fn=<AddBackward0>)
tensor([-1.0797], grad_fn=<AddBackward0>)
tensor([0.0859], grad_fn=<AddBackward0>)
tensor([0.0393], grad_fn=<AddBackward0>)
tensor([1.8167], grad_fn=<AddBackward0>)
tensor([0.8703], grad_fn=<AddBackward0>)
tensor([0.9992], grad_fn=<AddBackward0>)
tensor([-0.9320], grad_fn=<AddBackward0>)
tensor([-0.4594], grad_fn=<AddBackward0>)
tensor([-0.8157], grad_fn=<AddBackward0>)
tensor([-1.3112], grad_fn=<AddBackward0>)
tensor([-0.9319], grad_fn=<AddBackward0>)
tensor([-0.2340], grad_fn=<AddBackward0>)
tensor([-0.4658], grad_fn=<AddBackward0>)
tensor([0.5955], grad_fn=<AddBackward0>)
tensor([-0.5315], grad_fn=<AddBackward0>)
tensor([-0.8335], grad_fn=<AddBackward0>)
tensor([-0.1722], grad_fn=<AddBackward0>)
te