In [4]:
import torch
from torch import nn

In [5]:
model = nn.Linear(10, 1)

In [6]:
from adam_atan2_pytorch.adam_atan2 import AdamAtan2
from adam_atan2_pytorch.adam import Adam
from adam_atan2_pytorch.adopt import Adopt

In [7]:
opt = Adopt(model.parameters(), lr = 1e-4)

In [8]:
for _ in range(100):
    loss = model(torch.randn(10))
    print(loss)
    loss.backward()

    opt.step()
    opt.zero_grad()

tensor([-0.4808], grad_fn=<AddBackward0>)
tensor([0.2765], grad_fn=<AddBackward0>)
tensor([0.1107], grad_fn=<AddBackward0>)
tensor([0.3263], grad_fn=<AddBackward0>)
tensor([0.2531], grad_fn=<AddBackward0>)
tensor([-0.2419], grad_fn=<AddBackward0>)
tensor([1.0438], grad_fn=<AddBackward0>)
tensor([0.6945], grad_fn=<AddBackward0>)
tensor([0.0757], grad_fn=<AddBackward0>)
tensor([0.3172], grad_fn=<AddBackward0>)
tensor([-0.0769], grad_fn=<AddBackward0>)
tensor([1.3694], grad_fn=<AddBackward0>)
tensor([0.0730], grad_fn=<AddBackward0>)
tensor([0.8081], grad_fn=<AddBackward0>)
tensor([0.0917], grad_fn=<AddBackward0>)
tensor([-0.1095], grad_fn=<AddBackward0>)
tensor([0.4680], grad_fn=<AddBackward0>)
tensor([-0.7059], grad_fn=<AddBackward0>)
tensor([0.5573], grad_fn=<AddBackward0>)
tensor([-0.8133], grad_fn=<AddBackward0>)
tensor([-0.7308], grad_fn=<AddBackward0>)
tensor([0.3677], grad_fn=<AddBackward0>)
tensor([0.3250], grad_fn=<AddBackward0>)
tensor([0.3489], grad_fn=<AddBackward0>)
tensor([1